export const games = [
  {
    id: "1",
    title: "E.T.",
    platform: "Atari",
    rating: "1",
    reviews: ["101", "301"],
    genres: ["1"],
    theme: "",
  },
  {
    id: "2",
    title: "Super Mario Bros.",
    platform: "Nintendo(nes)",
    rating: "5.0",
    reviews: [],
    genres: ["2"],
    theme: "1",
  },
  {
    id: "3",
    title: "Ninja Gaiden",
    platform: "Nintendo(nes)",
    rating: "5.0",
    reviews: ["201"],
    genres: ["2", "3"],
    theme: "1",
  },
  {
    id: "4",
    title: "Resident Evil VII",
    platform: "Playstation 4",
    rating: "3.5",
    reviews: [],
    genres: ["3", "4"],
    theme: "2",
  },
  {
    id: "5",
    title: "Eternal Darkness",
    platform: "Gamecube",
    rating: "4.0",
    reviews: [],
    genres: ["4"],
    theme: "2",
  },
];
