version: "3.7"

services:
  db:
    build:
      dockerfile: Dockerfile.dev
      context: ./server/sql
    restart: "always"
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      DATABASE_HOST: project-metroid
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    expose: 
      - "3306"
    ports:
      - "3306:3306"

  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - "4000:4000"
    depends_on: 
      - db
    environment:
      DATABASE_HOST: project-metroid
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_PORT: 3306
    restart: on-failure
    volumes:
      # bookmark node_modules
      # don't try to override it
      - /home/node/app/node_modules
      # when we make a change of the server on our local machine
      # it will be reflected in the app dir in our container
      - ./server:/home/node/app
