FROM node:12-alpine

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node yarn.lock package.json ./

RUN yarn install

COPY --chown=node:node . .

EXPOSE 4000

CMD ["yarn", "start"]