version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true

  mysql:
    build:
      dockerfile: Dockerfile.dev
      context: ../sql
    restart: "always"
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
    expose:
      - "3306"
    ports:
      - "3306:3306"
