INSERT INTO genres (genre)
VALUES ('Adventure'),
  ('Arcade'),
  ("Beat 'em up"),
  ('Card and Board Game'),
  ('Fighting'),
  ("Hack 'N Slash"),
  ('Indie'),
  ('Music'),
  ('Pinball'),
  ('Platform'),
  ('Point and Click'),
  ('Puzzle'),
  ('Quiz / Trivia'),
  ('Racing'),
  ('Real Time Strategy'),
  ('Role Playing (RPG)'),
  ('Shooter'),
  ('Simulator'),
  ('Sport'),
  ('Strategy'),
  ('Tactical'),
  ('Visual Novel'),
  ('MOBA')