INSERT INTO platforms (platform)
VALUES ('Atari 2600'),
  ('Magnavox Odyssey 2'),
  ('Intellivision'),
  ('ColecoVision'),
  ('Atari 5200'),
  ('Vectrex'),
  ('Nintendo Family Computer (Famicom)'),
  ('Nintendo Entertainment System'),
  ('Family Computer Disk System'),
  ('Atari 7800'),
  ('Sega Master System'),
  ('Action Max'),
  ('Commodore 64 Games System'),
  ('PC Engine'),
  ('Sega Genesis'),
  ('TurboGrafx 16'),
  ('TurboGrafx CD'),
  ('PC Engine SuperGrafx'),
  ('Neo Geo AES'),
  ('Super Famicom'),
  ('Commodore CDTV'),
  ('Super Nintendo Entainment System (SNES)'),
  ('CD-i'),
  ('Sega CD'),
  ('Sega Pico'),
  ('Neo Geo CD'),
  ('Sega 32X'),
  ('Amiga CD32'),
  ('3DO Interactive Multiplayer'),
  ('Atari Jaguar'),
  ('Sega Saturn'),
  ('Playstation'),
  ('Atari Jaguar'),
  ('Nintendo 64'),
  ('Dreamcast'),
  ('Playstation 2'),
  ('Nintendo Gamecube'),
  ('Xbox'),
  ('Xbox 360'),
  ('Playstation 3'),
  ('Wii'),
  ('Wii U'),
  ('Playstation 4'),
  ('Xbox One'),
  ('Nintendo Switch'),
  ('Playstation 5'),
  ('PC'),
  ('Google Stadia');